### ISSUE TITLE
git imx6 repo fails?

### ISSUE THREAD

**Issue by ril3y** [dz0ny/snappy-cubox-i#1]
:~/snappy-cubox-i$ git clone git@github.com:SolidRun/u-boot-imx6.git
Cloning into 'u-boot-imx6'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Is the command that is failing.  Do you if I am doing something wrong?

**Comment by dz0ny** [comment]
Thats strange one, you can try cloning via https instead of port ssh port.
`git clone https://github.com/SolidRun/u-boot-imx6.git --depth 1`

**Comment by m-shibata** [comment]
Cloning with SSH ("git clone git@...") needs GitHub account and to upload ssh pub key.
Maybe prepare_kernel.sh shoud clone with https (use "git clone https...") when just download it?

Ref: Which remote URL should I use?
https://help.github.com/articles/which-remote-url-should-i-use/
